[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[env.production]
  VITE_SUPABASE_URL = "https://ugbvucelkovciaenodee.supabase.co"
  VITE_SUPABASE_KEY = "sb_publishable_JXLx8Fy_HV5wOvYsfFhNvQ_DnqnjI9f"
